### ISSUE TITLE
Preview / Export does not render writings on 3.0 beta

### ISSUE THREAD

**Issue by xnhp** [bordaigorl/remy#46] opened 2022-11-04 13:42 UTC
Hi,

first of all, thank you so much for making this nice piece of software.

Just wanted to let you know, on 3.0.1192, any documents that have been edited since on the new firmware will fail to render the writings properly. It seems anything written when on the new firmware is not displayed at all, but I'm not certain.

This is probably due to breaking changes in the reMarkable firmware (introducing infinite pages, etc).

Best,
Ben

**Comment by bordaigorl** [comment] 2022-11-04 21:59
This is unfortunately to be expected :(
I've seen reports of people saying the underlying format has changed and I don't know of any attempt at reverse engineering it yet.
I don't have 3.0 yet, but once it gets an official release I will try to see what I can do to support it in Remy.
Until then, Remy just does not support 3.0.
(maybe I should add a notice to the readme...)

Thanks for reporting!

**Comment by xnhp** [comment] 2022-11-05 18:43
Yeah, it's not surprising. Just wanted to leave a note here for completess
sake s.t. somebody wondering why his setup doesn't work knows.

Again, thanks for your work :).

**Comment by bordaigorl** [comment] 2023-01-28 16:16
Closing as duplicate of #49 (follow that issue for updates)

**Closed by bordaigorl** 2023-01-28 16:16 UTC
